#!/usr/bin/env python
import sys, os, re
from subprocess import check_output
# Collect the parameters
commit_msg_filepath = sys.argv[1]
with open(commit_msg_filepath, 'r') as f:
    content = f.read()
    result = re.match('TEAM6-(.*)', content)
    if result == None:
        print "commit-msg: ERROR! The commit message must contain a valid JIRA issue number"
        sys.exit(1)
